export interface InventoryItem {
  sku: string;
  name: string;
  image: string;
  category: string;
  stock: number;
  price: number;
}

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    sku: "PROD-001",
    name: "Producto A",
    image: "/img-prod.webp",
    category: "Electrónica",
    stock: 50,
    price: 1200,
  },
  {
    sku: "PROD-002",
    name: "Producto B",
    image: "/img-prod.webp",
    category: "Ropa",
    stock: 120,
    price: 850,
  },
  {
    sku: "PROD-003",
    name: "Producto C",
    image: "/img-prod.webp",
    category: "Hogar",
    stock: 15,
    price: 2100,
  },
  {
    sku: "PROD-004",
    name: "Producto D",
    image: "/img-prod.webp",
    category: "Alimentos",
    stock: 200,
    price: 400,
  },
  {
    sku: "PROD-005",
    name: "Producto E",
    image: "/img-prod.webp",
    category: "Electrónica",
    stock: 30,
    price: 1500,
  },
  {
    sku: "PROD-006",
    name: "Producto F",
    image: "/img-prod.webp",
    category: "Ropa",
    stock: 0,
    price: 600,
  },
  {
    sku: "PROD-007",
    name: "Producto G",
    image: "/img-prod.webp",
    category: "Hogar",
    stock: 85,
    price: 3000,
  },
  {
    sku: "PROD-008",
    name: "Producto H",
    image: "/img-prod.webp",
    category: "Alimentos",
    stock: 40,
    price: 1100,
  },
  {
    sku: "PROD-009",
    name: "Producto I",
    image: "/img-prod.webp",
    category: "Otros",
    stock: 10,
    price: 900,
  },
  {
    sku: "PROD-010",
    name: "Producto J",
    image: "/img-prod.webp",
    category: "Electrónica",
    stock: 65,
    price: 1800,
  },
  {
  sku: "PROD-011",
  name: "Producto K",
  image: "/img-prod.webp",
  category: "Ropa",
  stock: 20,
  price: 800,
},
{
  sku: "PROD-012",
  name: "Producto L",
  image: "/img-prod.webp",
  category: "Hogar",
  stock: 50,
  price: 2500,
},
{
  sku: "PROD-013",
  name: "Producto M",
  image: "/img-prod.webp",
  category: "Alimentos",
  stock: 30,
  price: 1200,
},
{
  sku: "PROD-014",
  name: "Producto N",
  image: "/img-prod.webp",
  category: "Otros",
  stock: 15,
  price: 700,
},
{
  sku: "PROD-015",
  name: "Producto O",
  image: "/img-prod.webp",
  category: "Electrónica",
  stock: 70,
  price: 1900,
},
{
  sku: "PROD-016",
  name: "Producto P",
  image: "/img-prod.webp",
  category: "Ropa",
  stock: 25,
  price: 900,
},
{
  sku: "PROD-017",
  name: "Producto Q",
  image: "/img-prod.webp",
  category: "Hogar",
  stock: 60,
  price: 2800,
},
{
  sku: "PROD-018",
  name: "Producto R",
  image: "/img-prod.webp",
  category: "Alimentos",
  stock: 35,
  price: 1300,
},
{
  sku: "PROD-019",
  name: "Producto S",
  image: "/img-prod.webp",
  category: "Otros",
  stock: 18,
  price: 750,
},
{
  sku: "PROD-020",
  name: "Producto T",
  image: "/img-prod.webp",
  category: "Electrónica",
  stock: 75,
  price: 2000,
},
];



export const MOCK_BUSINESS: InventoryItem[] = [
  {
    sku: "PROD-001",
    name: "Producto A",
    image: "/img-prod.webp",
    category: "Electrónica",
    stock: 50,
    price: 1200,
  },
  {
    sku: "PROD-002",
    name: "Producto B",
    image: "/img-prod.webp",
    category: "Ropa",
    stock: 120,
    price: 850,
  },
  {
    sku: "PROD-003",
    name: "Producto C",
    image: "/img-prod.webp",
    category: "Hogar",
    stock: 15,
    price: 2100,
  },
  {
    sku: "PROD-004",
    name: "Producto D",
    image: "/img-prod.webp",
    category: "Alimentos",
    stock: 200,
    price: 400,
  },
  {
    sku: "PROD-005",
    name: "Producto E",
    image: "/img-prod.webp",
    category: "Electrónica",
    stock: 30,
    price: 1500,
  },
  {
    sku: "PROD-006",
    name: "Producto F",
    image: "/img-prod.webp",
    category: "Ropa",
    stock: 0,
    price: 600,
  },
  {
    sku: "PROD-007",
    name: "Producto G",
    image: "/img-prod.webp",
    category: "Hogar",
    stock: 85,
    price: 3000,
  },
  {
    sku: "PROD-008",
    name: "Producto H",
    image: "/img-prod.webp",
    category: "Alimentos",
    stock: 40,
    price: 1100,
  },
  {
    sku: "PROD-009",
    name: "Producto I",
    image: "/img-prod.webp",
    category: "Otros",
    stock: 10,
    price: 900,
  },
  {
    sku: "PROD-010",
    name: "Producto J",
    image: "/img-prod.webp",
    category: "Electrónica",
    stock: 65,
    price: 1800,
  },
  {
  sku: "PROD-011",
  name: "Producto K",
  image: "/img-prod.webp",
  category: "Ropa",
  stock: 20,
  price: 800,
},
{
  sku: "PROD-012",
  name: "Producto L",
  image: "/img-prod.webp",
  category: "Hogar",
  stock: 50,
  price: 2500,
},

];

